version: '3'
services:
  db:
    restart: always
    image: sameersbn/postgresql
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PG_PASSWORD="postgres"
      - DB_NAME=ClairDb
      - PG_TRUST_LOCALNET=true

  clair:
    restart: always
    image: 434313288222.dkr.ecr.us-east-1.amazonaws.com/prod/ellucian-clair:0.0.4
    ports:
      - "6060:6060"
    environment:
      - config_base64=LS0tCmNsYWlyOgogIGRhdGFiYXNlOgogICAgIyBEYXRhYmFzZSBkcml2ZXIKICAgIHR5cGU6IHBnc3FsCiAgICBvcHRpb25zOgogICAgICAjIFBvc3RncmVTUUwgQ29ubmVjdGlvbiBzdHJpbmcKICAgICAgIyBodHRwczovL3d3dy5wb3N0Z3Jlc3FsLm9yZy9kb2NzL2N1cnJlbnQvc3RhdGljL2xpYnBxLWNvbm5lY3QuaHRtbCNMSUJQUS1DT05OU1RSSU5HCiAgICAgIHNvdXJjZTogaG9zdD0xOTIuMTY4Ljk5LjEwMCBkYm5hbWU9Q2xhaXJEYiB1c2VyPXBvc3RncmVzIHBhc3N3b3JkPWFkbWluIHNzbG1vZGU9ZGlzYWJsZQoKICAgICAgIyBOdW1iZXIgb2YgZWxlbWVudHMga2VwdCBpbiB0aGUgY2FjaGUKICAgICAgIyBWYWx1ZXMgdW5saWtlbHkgdG8gY2hhbmdlIChlLmcuIG5hbWVzcGFjZXMpIGFyZSBjYWNoZWQgaW4gb3JkZXIgdG8gc2F2ZSBwcmV2ZW50IG5lZWRsZXNzIHJvdW5kdHJpcHMgdG8gdGhlIGRhdGFiYXNlLgogICAgICBjYWNoZXNpemU6IDE2Mzg0CgogICAgICAjIDMyLWJpdCBVUkwtc2FmZSBiYXNlNjQga2V5IHVzZWQgdG8gZW5jcnlwdCBwYWdpbmF0aW9uIHRva2VucwogICAgICAjIElmIG9uZSBpcyBub3QgcHJvdmlkZWQsIGl0IHdpbGwgYmUgZ2VuZXJhdGVkLgogICAgICAjIE11bHRpcGxlIGNsYWlyIGluc3RhbmNlcyBpbiB0aGUgc2FtZSBjbHVzdGVyIG5lZWQgdGhlIHNhbWUgdmFsdWUuCiAgICAgIHBhZ2luYXRpb25rZXk6CgogIGFwaToKICAgICMgdjMgZ3JwYy9SRVNUZnVsIEFQSSBzZXJ2ZXIgYWRkcmVzcwogICAgYWRkcjogIjAuMC4wLjA6NjA2MCIKCiAgICAjIEhlYWx0aCBzZXJ2ZXIgYWRkcmVzcwogICAgIyBUaGlzIGlzIGFuIHVuZW5jcnlwdGVkIGVuZHBvaW50IHVzZWZ1bCBmb3IgbG9hZCBiYWxhbmNlcnMgdG8gY2hlY2sgdG8gaGVhbHRoaW5lc3Mgb2YgdGhlIGNsYWlyIHNlcnZlci4KICAgIGhlYWx0aGFkZHI6ICIwLjAuMC4wOjYwNjEiCgogICAgIyBEZWFkbGluZSBiZWZvcmUgYW4gQVBJIHJlcXVlc3Qgd2lsbCByZXNwb25kIHdpdGggYSA1MDMKICAgIHRpbWVvdXQ6IDkwMHMKCiAgICAjIE9wdGlvbmFsIFBLSSBjb25maWd1cmF0aW9uCiAgICAjIElmIHlvdSB3YW50IHRvIGVhc2lseSBnZW5lcmF0ZSBjbGllbnQgY2VydGlmaWNhdGVzIGFuZCBDQXMsIHRyeSB0aGUgZm9sbG93aW5nIHByb2plY3RzOgogICAgIyBodHRwczovL2dpdGh1Yi5jb20vY29yZW9zL2V0Y2QtY2EKICAgICMgaHR0cHM6Ly9naXRodWIuY29tL2Nsb3VkZmxhcmUvY2Zzc2wKICAgIHNlcnZlcm5hbWU6CiAgICBjYWZpbGU6CiAgICBrZXlmaWxlOgogICAgY2VydGZpbGU6CgogIHdvcmtlcjoKICAgIG5hbWVzcGFjZV9kZXRlY3RvcnM6CiAgICAgIC0gb3MtcmVsZWFzZQogICAgICAtIGxzYi1yZWxlYXNlCiAgICAgIC0gYXB0LXNvdXJjZXMKICAgICAgLSBhbHBpbmUtcmVsZWFzZQogICAgICAtIHJlZGhhdC1yZWxlYXNlCgogICAgZmVhdHVyZV9saXN0ZXJzOgogICAgICAtIGFwawogICAgICAtIGRwa2cKICAgICAgLSBycG0KCiAgdXBkYXRlcjoKICAgICMgRnJlcXVlbmN5IHRoZSBkYXRhYmFzZSB3aWxsIGJlIHVwZGF0ZWQgd2l0aCB2dWxuZXJhYmlsaXRpZXMgZnJvbSB0aGUgZGVmYXVsdCBkYXRhIHNvdXJjZXMKICAgICMgVGhlIHZhbHVlIDAgZGlzYWJsZXMgdGhlIHVwZGF0ZXIgZW50aXJlbHkuCiAgICBpbnRlcnZhbDogMmgKICAgIGVuYWJsZWR1cGRhdGVyczoKICAgICAgLSBkZWJpYW4KICAgICAgLSB1YnVudHUKICAgICAgLSByaGVsCiAgICAgIC0gb3JhY2xlCiAgICAgIC0gYWxwaW5lCgogIG5vdGlmaWVyOgogICAgIyBOdW1iZXIgb2YgYXR0ZW1wdHMgYmVmb3JlIHRoZSBub3RpZmljYXRpb24gaXMgbWFya2VkIGFzIGZhaWxlZCB0byBiZSBzZW50CiAgICBhdHRlbXB0czogMwoKICAgICMgRHVyYXRpb24gYmVmb3JlIGEgZmFpbGVkIG5vdGlmaWNhdGlvbiBpcyByZXRyaWVkCiAgICByZW5vdGlmeWludGVydmFsOiAyaAoKICAgIGh0dHA6CiAgICAgICMgT3B0aW9uYWwgZW5kcG9pbnQgdGhhdCB3aWxsIHJlY2VpdmUgbm90aWZpY2F0aW9ucyB2aWEgUE9TVCByZXF1ZXN0cwogICAgICBlbmRwb2ludDoKCiAgICAgICMgT3B0aW9uYWwgUEtJIGNvbmZpZ3VyYXRpb24KICAgICAgIyBJZiB5b3Ugd2FudCB0byBlYXNpbHkgZ2VuZXJhdGUgY2xpZW50IGNlcnRpZmljYXRlcyBhbmQgQ0FzLCB0cnkgdGhlIGZvbGxvd2luZyBwcm9qZWN0czoKICAgICAgIyBodHRwczovL2dpdGh1Yi5jb20vY2xvdWRmbGFyZS9jZnNzbAogICAgICAjIGh0dHBzOi8vZ2l0aHViLmNvbS9jb3Jlb3MvZXRjZC1jYQogICAgICBzZXJ2ZXJuYW1lOgogICAgICBjYWZpbGU6CiAgICAgIGtleWZpbGU6CiAgICAgIGNlcnRmaWxlOgoKICAgICAgIyBPcHRpb25hbCBIVFRQIFByb3h5OiBtdXN0IGJlIGEgdmFsaWQgVVJMIChpbmNsdWRpbmcgdGhlIHNjaGVtZSkuCiAgICAgIHByb3h5Og==

  clair-scanner:
    restart: always
    #image: 434313288222.dkr.ecr.us-east-1.amazonaws.com/prod/clair-scanner:0.0.9
    build:
      context: '../clair-scanner'
    environment:
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/121717378798/ellucian-clair-index-requests
      - REGION=us-east-1
      - BUCKET=clair-scan-results
      - CLAIR_ADDR=192.168.99.100:6060
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
